AST-IR split
butte-rs/butte pull request #28
Opened 2020-01-16 23:35 UTC by magnet

This MR introduces a set of IR (Intermediate Representation) types that AST types are converted into before going through codegen.  Some sort of semantic context is required when emitting the code for unions from a table -- and keeping an approach where we generate with `ToTokens` impl requires the types to be self-contained to generate tokens. 

A first commit introduces a new module `parse` for parsing and AST types; the second commit introduces an `ir` module with IR types and a transform module that transforms an AST to IR types. Codegen is adapted to use IR types.

Design choices:
* IR type idents always contain the namespace, and codegen is responsible for emitting the "simple" name. This is to help debugging/error reporting.
* The schema to IR transform can take several passes -- when a type reference is not known and valid yet, it cannot be used by a struct -- though a table does not need to get the type fully defined (this is because tables can be recursive).  This logic could likely be improved, but was easy to get working.

IR idents and dotted idents use `Cow<'_, str>` because we sometimes need to generate idents in the transform code and thus transfer ownership (e.g, synthetic enum field preceding unions in tables). It might be more practical, but likely less performant, to use `String` everywhere instead.

Error reporting could be improved; ideally the AST would contain spans and we could nicely report errors.

I've removed code gen for some elements IIRC, notably `Includes` (need to rework them properly), `RootTypes` (not sure they worked), and `RPCMethods` (I think this should be the responsibility of `tonic-build` integration).

2020-01-16 23:39 UTC, magnet commented
ah, 1.39.0 :).  1.40.0 has this nice `std::mem::take(&mut xx)` that is a shorthand for `replace` for types that implement `Default`.

2020-01-16 23:53 UTC, lovesegfault commented
> ah, 1.39.0 :). 1.40.0 has this nice `std::mem::take(&mut xx)` that is a shorthand for `replace` for types that implement `Default`.

We can move to 1.40; we're not super serious about MSRV right now :)

2020-01-22 21:16 UTC, cpcloud requested changes

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +    Namespace(IrNamespace<'a>),
How do you feel about renaming `parse/types.rs` to `ast/types.rs`, aliasing that module here to `ast` and then using `ast::` inside this module so that we can avoid having to add `Ir` to the prefix of every type's name in this module?

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +    pub fn ident(&self) -> &IrDottedIdent<'a> {
I think you can elide the lifetime here.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +    pub fn namespace(&self) -> Option<IrDottedIdent<'a>> {
Same, the lifetime shouldn't be necessary here.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +    pub fn as_namespace(&self) -> Option<&IrNamespace<'a>> {
Lifetime not needed here.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +    pub fn as_namespace(&self) -> Option<&IrNamespace<'a>> {
If your approach here is "if the lifetime is required at all, write it in every method" I'm fine with that too!

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +    _phantom: &'a (),
Is there a reason that you need this here? I think an empty struct would also do. Then you don't need to write down the lifetime when using this struct as a field.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +impl Default for IrMetadata<'_> {
If you use an empty struct for `IrMetadata` then you can derive this impl.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +pub enum IrCustomType<'a> {
Can we call this `UserDefinedType` instead?

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +    _phantom: &'a (),
Similar question as for `IrMetadata`: do we need the field here or can we use an empty struct for now?

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +impl<'a> IrType<'a> {
Can use `'_` here.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +impl<'a> std::convert::TryFrom<&Type<'a>> for IrEnumBaseType {
Should be able to use `'_` here and in the method definition.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +            parts: s.split('.').map(IrIdent::from).collect(),
Could use `Into::into` here

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +        IrDottedIdent {
Can use `Self` here.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +    pub fn namespace(&self) -> Option<IrDottedIdent<'a>> {
Can use `Self` her instead of `IrDottedIdent<'a>`

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +impl<'a> Display for IrIdent<'a> {
Can use `'_` here.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/codegen.rs
> -        let code = elements
I had fun writing this, but thank goodness it's gone.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/types.rs
> +    pub fn simple(&self) -> &IrIdent<'a> {
Can we call this `leaf`?

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/transform.rs
> +    }
line break here

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/transform.rs
> +        Ok(IrRoot { nodes })
Can use `Self` here.

2020-01-22 21:16 UTC, cpcloud commented on butte-build/src/ir/transform.rs
> +            let ns_depth = ns.ident.parts.len();
Probably ok to make a `depth` method on `IrNamespace`

2020-01-22 21:16 UTC, cpcloud commented
@magnet Most of my comments are small nits, none blocking.

2020-02-24 19:10 UTC, magnet commented
Closed in favour of #31

I took most comment into account, though I did forget some after I was done reworking the history.  If you don't mind please review the new one and let me know if you still feel strongly about changes there.

2020-02-24 19:10 UTC, closed without merging